apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: flannel2-conf
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "flannel",
    "subnetFile": "/run/flannel/flannel2.env",
    "dataDir": "/var/lib/cni/flannel2",
    "delegate": {
      "bridge": "kbr1"
    }
  }'
