- name: Create Testground overlay control network
  docker_network:
    name: control
    driver: overlay
    attachable: yes
    enable_ipv6: no
    ipam_config:
      - subnet: 192.168.0.0/16

- name: Start Redis service
  docker_swarm_service:
    name: testground-redis
    image: "redis:latest"
    command: redis-server
    args:
      - --notify-keyspace-events $szxK
      - --save ""
      - --appendonly no
    networks:
      - control
    placement:
      constraints:
        - node.labels.TGRole == redis

- name: Start sidecar service
  docker_swarm_service:
    name: testground-sidecar
    image: "ipfs/testground:latest"
    mode: global
    command: testground
    args:
      - sidecar
      - --runner docker
    env:
      REDIS_HOST: "testground-redis"
    networks:
      - control
    placement:
      constraints:
        - node.labels.TGRole == worker

