# Pause for 10 seconds for worker nodes to connect to master
- pause:
    seconds: 10

- name: Create Testground overlay control network
  docker_network:
    name: control
    driver: overlay
    attachable: yes
    enable_ipv6: no
    ipam_config:
      - subnet: 192.168.0.0/16

- pause:
    seconds: 5

# Propagate `control` network on all hosts in the Swarm
- name: Start sleep service
  docker_swarm_service:
    name: sleep
    image: "alpine"
    mode: global
    command: sleep 36000
    networks:
      - control

- pause:
    seconds: 5

- name: Start Redis service
  docker_swarm_service:
    name: testground-redis
    image: "redis:latest"
    command: redis-server
    args:
      - --save ""
      - --appendonly no
    networks:
      - control
    placement:
      constraints:
        - node.labels.TGRole == redis

# Pause for 20 seconds after starting redis
- pause:
    seconds: 20
