- name: Join Swarm Cluster as a Worker
  docker_swarm:
    state: join
    advertise_addr: "{{ ansible_all_ipv4_addresses | ipaddr('172.16.0.0/16') | first }}"
    join_token: "{{ token }}"
    remote_addrs: [ "{{ manager }}:2377" ]

# Pause for 10 seconds for worker nodes to connect to master
- pause:
    seconds: 10
